name: Deploy Crisp App

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  dockertag: "0.2"
  crisprg: "crisprg"
  crispaks: "crispaks"
  crispsa: "crispsadsavitz"
  crispreg: "crispreg"
  crispsablobname: "crisp"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Deploy Infrastructure
        run: |
          az group create --name $crisprg --location eastus2
          #az group deployment create --resource-group $crisprg --template-file arm_templates/aks.json --parameters aks_cluster_name=$crispaks
          #az group deployment create --resource-group $crisprg --template-file arm_templates/sa.json --parameters storage_account_name=$crispsa
          #az group deployment create --resource-group $crisprg --template-file arm_templates/acr.json --parameters registry_name=$crispreg
          #az storage account update --name $crispsa --resource-group $crisprg --default-action Allow --bypass AzureServices

      - name: Build the Docker image
        run: |
          az acr login --name $crispreg
          docker build . --file Dockerfile --tag $crispreg.azurecr.io/crisp:$dockertag
          docker push $crispreg.azurecr.io/crisp:$dockertag

      - name: Configure kubectl
        run: |
          az aks get-credentials --resource-group $crisprg --name $crispaks --overwrite-existing

      - name: Run kubectl command
        run: |
          kubectl get pods --all-namespaces

          kubectl get secret acrsecret >/dev/null 2>&1
          if [ $? -ne 0 ]; then
            echo "Secret acrsecret does not exist. Creating it..."
            kubectl create secret docker-registry acrsecret --docker-server=crispreg.azurecr.io --docker-username=cfff6db8-6ea9-4769-a9c4-3f5f2caa71fb --docker-password=${{ secrets.AZURE_CLIENT_SECRET }} --docker-email=savitz.daniel@gmail.com
          else
            echo "Secret acrsecret already exists. Skipping creation."
          fi

          kubectl get secret crispsakey-secret >/dev/null 2>&1
          if [ $? -ne 0 ]; then
            crispsakey=$(az storage account keys list --resource-group $crisprg --account-name $crispsa --query '[0].value' --output tsv)
            echo "##[set-output name=crispsakey;]$crispsakey"
            kubectl create secret generic crispsakey-secret --from-literal=crispsakey=$crispsakey 
          else
            echo "Secret crispsakey-secret already exists. Skipping creation."
          fi

      - name: create k8s deployment
        run: |
          kubectl get pods --all-namespaces
          sed -i "s:{{crispacr}}:$crispreg:" deployment.yaml
          sed -i "s:{{tag}}:$dockertag:" deployment.yaml
          sed -i "s:{{crispsa}}:$crispsa:" deployment.yaml
          sed -i "s:{{crispsablobname}}:$crispsablobname:" deployment.yaml
          kubectl delete -f deployment.yaml
          kubectl apply -f deployment.yaml
          sleep 20
          PODS=$(kubectl get pods -l app=crisp -o jsonpath='{.items[*].metadata.name}')
          # Loop through each pod and get logs
          for POD in $PODS; do
            echo "Logs for pod: $POD"
            kubectl logs $POD
          done
          #kubectl logs
