name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag crispreg2.azurecr.io/crisp:0.1
        docker push crispreg2.azurecr.io/crisp:0.1

    - name: Configure kubectl
      run: |
        az aks get-credentials --resource-group Crisp2_group --name Crisp --overwrite-existing

    - name: Run kubectl command
      run: |
        kubectl get pods --all-namespaces
